/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.qlthitracnghiem.GUI.ThongKe;

import com.example.qlthitracnghiem.GUI.Exam.DoExamJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Asus
 */
public class MainThongKePanel extends javax.swing.JPanel {

    /**
     * Creates new form MainThongKePanel
     */
    public MainThongKePanel() {
        initComponents();
        initCartForThongKe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chonThongKePanel = new javax.swing.JPanel();
        tieuDeThongKePN = new javax.swing.JPanel();
        tieuDePN = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        searchUserPN = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        searchUserThongKeTF = new javax.swing.JTextField();
        searchUserThongKeCB = new javax.swing.JComboBox<>();
        thongTinUserThongKePN = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        userIdThongKeLB = new javax.swing.JLabel();
        userNameThongKeLB = new javax.swing.JLabel();
        fullNameThongKeLB = new javax.swing.JLabel();
        emailThongKeLB = new javax.swing.JLabel();
        luaChonThongKe1 = new javax.swing.JPanel();
        thongKeTongPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        thongKeTongLB = new javax.swing.JLabel();
        thongKeBaiThiPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        thongKeBaiThiLB = new javax.swing.JLabel();
        luaChonThongKe2 = new javax.swing.JPanel();
        thongKeSoSanhPanel = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        thongKeSoSanhLB = new javax.swing.JLabel();
        thongKeLichSuPanel = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        thongKeLichSuLB = new javax.swing.JLabel();
        hienThiThongKePanel = new javax.swing.JPanel();
        thongKeBaiThiCardPanel = new javax.swing.JPanel();
        thongKeBaiThiCardLB = new javax.swing.JLabel();
        thongKeBaiThiCardPN = new javax.swing.JPanel();
        progressThongKeBaiThiCardPN = new javax.swing.JPanel();
        scoreThongKeBaiThiPN = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        JLabel10 = new javax.swing.JLabel();
        highScoreThongKeBaiThiLB = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lowScoreThongKeBaiThiLB = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        targetThongKeBaiThiLB = new javax.swing.JLabel();
        progressThongKeBaiThiPN = new javax.swing.JPanel();
        cauTraLoiDungThongKeBaiThiLB = new javax.swing.JLabel();
        cauTraLoiDungTKBaiThiPB = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        cauTraLoiSaiTKBaiThiPB = new javax.swing.JProgressBar();
        jLabel13 = new javax.swing.JLabel();
        thoiGianLamBaiTKBaiPB = new javax.swing.JProgressBar();
        jLabel15 = new javax.swing.JLabel();
        thiLaiTKBaiThiPB = new javax.swing.JProgressBar();
        searchThongKeBaiThiCardPN = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        topicSearchComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        topicSearchTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        examSearchTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        thongKeSoSanhCardPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        searchSoSanhKetQuaPN = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        searchTopicSoSanhKetQuaTF = new javax.swing.JTextField();
        searchTopicSoSanhKetQuaCB = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        searchExamSoSanhKetQuaTF = new javax.swing.JTextField();
        searchExamSoSanhKetQuaCB = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        searchUserSoSanhKetQuaTF = new javax.swing.JTextField();
        searchUserSoSanhKetQuaCB = new javax.swing.JComboBox<>();
        ketQuaTimKiemSoSanhKetQuaLB = new javax.swing.JLabel();
        ketQuaUser1PN = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        soCauDungUser1PB = new javax.swing.JProgressBar();
        jLabel24 = new javax.swing.JLabel();
        soCauTraLoiSaiUser1PB = new javax.swing.JProgressBar();
        jLabel28 = new javax.swing.JLabel();
        thoiGianHTUser1PB = new javax.swing.JProgressBar();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        highScoreUser1LB = new javax.swing.JLabel();
        ketQuaUser2PN = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        soCauDungUser2PB = new javax.swing.JProgressBar();
        jLabel35 = new javax.swing.JLabel();
        soCauTraLoiSaiUser2PB = new javax.swing.JProgressBar();
        jLabel36 = new javax.swing.JLabel();
        thoiGianHTUser2PB = new javax.swing.JProgressBar();
        jPanel20 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        highScoreUser2LB = new javax.swing.JLabel();
        thongKeLichSuCardPanel = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        lichSuBaiThiPN = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        thongKeTongCardPanel = new javax.swing.JPanel();
        tieuDeThongKeTongPN = new javax.swing.JPanel();
        thongKeTongCardLB = new javax.swing.JLabel();
        searchThongKeTongPN = new javax.swing.JPanel();
        searchTopicAndExamTKTongPN = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        searchTopicTKTongCB = new javax.swing.JComboBox<>();
        searchTopicTKTongTF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        searchExamTKTongTF = new javax.swing.JTextField();
        thongKeTongScorePanel = new javax.swing.JPanel();
        scoreLB = new javax.swing.JLabel();
        highScorePN = new javax.swing.JPanel();
        highScoreLB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lowScorePN = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        averageScorePN = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        thongKeTongProgressPanel = new javax.swing.JPanel();
        tBThoiGianHoanThanhLB = new javax.swing.JLabel();
        tBThoiGianHoanThanhPB = new javax.swing.JProgressBar();
        tBSoLanThiLaiLB = new javax.swing.JLabel();
        tBSoLanThiLaiPB = new javax.swing.JProgressBar();
        tBCauTraLoiDungLB = new javax.swing.JLabel();
        tBCauTraLoiDungPB = new javax.swing.JProgressBar();
        tBCauTraLoiSaiLB = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        pTHoanThanhDeThiLB = new javax.swing.JLabel();
        pTHoanThanhDeThiPB = new javax.swing.JProgressBar();
        pTKhongHoanThanhDeThiLB = new javax.swing.JLabel();
        pTKhongHoanThanhDeThiPB = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 628));
        setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        chonThongKePanel.setBackground(new java.awt.Color(255, 255, 255));
        chonThongKePanel.setLayout(new java.awt.GridLayout(3, 0, 0, 15));

        tieuDeThongKePN.setBackground(new java.awt.Color(255, 255, 255));
        tieuDeThongKePN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        tieuDeThongKePN.setLayout(new java.awt.BorderLayout(0, 2));

        tieuDePN.setBackground(new java.awt.Color(255, 255, 255));
        tieuDePN.setPreferredSize(new java.awt.Dimension(523, 140));
        tieuDePN.setLayout(new java.awt.GridLayout(2, 0));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Thống Kê Tổng Và Cá Nhân Thành Viên");
        jLabel27.setPreferredSize(new java.awt.Dimension(457, 40));
        tieuDePN.add(jLabel27);

        searchUserPN.setBackground(new java.awt.Color(204, 204, 204));
        searchUserPN.setPreferredSize(new java.awt.Dimension(511, 30));
        searchUserPN.setLayout(new java.awt.BorderLayout());

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Search User:");
        jLabel22.setPreferredSize(new java.awt.Dimension(111, 30));
        searchUserPN.add(jLabel22, java.awt.BorderLayout.PAGE_START);

        searchUserThongKeTF.setBackground(new java.awt.Color(255, 255, 255));
        searchUserThongKeTF.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        searchUserThongKeTF.setForeground(new java.awt.Color(0, 0, 0));
        searchUserThongKeTF.setPreferredSize(new java.awt.Dimension(64, 15));
        searchUserThongKeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserThongKeTFActionPerformed(evt);
            }
        });
        searchUserPN.add(searchUserThongKeTF, java.awt.BorderLayout.CENTER);

        searchUserThongKeCB.setBackground(new java.awt.Color(204, 204, 204));
        searchUserThongKeCB.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        searchUserThongKeCB.setForeground(new java.awt.Color(0, 0, 0));
        searchUserThongKeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchUserThongKeCB.setPreferredSize(new java.awt.Dimension(180, 25));
        searchUserPN.add(searchUserThongKeCB, java.awt.BorderLayout.LINE_END);

        tieuDePN.add(searchUserPN);

        tieuDeThongKePN.add(tieuDePN, java.awt.BorderLayout.CENTER);

        thongTinUserThongKePN.setBackground(new java.awt.Color(0, 0, 0));
        thongTinUserThongKePN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0)));
        thongTinUserThongKePN.setPreferredSize(new java.awt.Dimension(511, 110));
        thongTinUserThongKePN.setLayout(new java.awt.GridLayout(1, 0, 2, 0));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new java.awt.GridLayout(4, 0));

        jLabel31.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("UserId:");
        jPanel18.add(jLabel31);

        jLabel32.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("UserName:");
        jPanel18.add(jLabel32);

        jLabel33.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Fullname:");
        jPanel18.add(jLabel33);

        jLabel37.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Email:");
        jPanel18.add(jLabel37);

        thongTinUserThongKePN.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new java.awt.GridLayout(4, 0));

        userIdThongKeLB.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        userIdThongKeLB.setForeground(new java.awt.Color(0, 0, 0));
        userIdThongKeLB.setText("1");
        jPanel19.add(userIdThongKeLB);

        userNameThongKeLB.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        userNameThongKeLB.setForeground(new java.awt.Color(0, 0, 0));
        userNameThongKeLB.setText("Tang Thanh Trung");
        jPanel19.add(userNameThongKeLB);

        fullNameThongKeLB.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        fullNameThongKeLB.setForeground(new java.awt.Color(0, 0, 0));
        fullNameThongKeLB.setText("Tang Thanh Trung");
        jPanel19.add(fullNameThongKeLB);

        emailThongKeLB.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        emailThongKeLB.setForeground(new java.awt.Color(0, 0, 0));
        emailThongKeLB.setText("thanhtrung22052004@gmail,com");
        jPanel19.add(emailThongKeLB);

        thongTinUserThongKePN.add(jPanel19);

        tieuDeThongKePN.add(thongTinUserThongKePN, java.awt.BorderLayout.PAGE_END);

        chonThongKePanel.add(tieuDeThongKePN);

        luaChonThongKe1.setBackground(new java.awt.Color(255, 255, 255));
        luaChonThongKe1.setPreferredSize(new java.awt.Dimension(700, 207));
        luaChonThongKe1.setLayout(new java.awt.GridLayout(1, 0, 20, 5));

        thongKeTongPanel.setBackground(new java.awt.Color(255, 153, 153));
        thongKeTongPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        thongKeTongPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKeTongPanelMouseClicked(evt);
            }
        });

        thongKeTongLB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thongKeTongLB.setForeground(new java.awt.Color(0, 0, 0));
        thongKeTongLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongKeTongLB.setText("Thống Kê Tổng");

        javax.swing.GroupLayout thongKeTongPanelLayout = new javax.swing.GroupLayout(thongKeTongPanel);
        thongKeTongPanel.setLayout(thongKeTongPanelLayout);
        thongKeTongPanelLayout.setHorizontalGroup(
            thongKeTongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeTongPanelLayout.createSequentialGroup()
                .addGroup(thongKeTongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(thongKeTongPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(thongKeTongLB, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                .addContainerGap())
        );
        thongKeTongPanelLayout.setVerticalGroup(
            thongKeTongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongKeTongPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thongKeTongLB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        luaChonThongKe1.add(thongKeTongPanel);

        thongKeBaiThiPanel.setBackground(new java.awt.Color(153, 255, 153));
        thongKeBaiThiPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        thongKeBaiThiPanel.setForeground(new java.awt.Color(0, 0, 0));
        thongKeBaiThiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKeBaiThiPanelMouseClicked(evt);
            }
        });

        thongKeBaiThiLB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thongKeBaiThiLB.setForeground(new java.awt.Color(0, 0, 0));
        thongKeBaiThiLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongKeBaiThiLB.setText("Thống Kê Bài Thi");

        javax.swing.GroupLayout thongKeBaiThiPanelLayout = new javax.swing.GroupLayout(thongKeBaiThiPanel);
        thongKeBaiThiPanel.setLayout(thongKeBaiThiPanelLayout);
        thongKeBaiThiPanelLayout.setHorizontalGroup(
            thongKeBaiThiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeBaiThiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thongKeBaiThiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(thongKeBaiThiLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        thongKeBaiThiPanelLayout.setVerticalGroup(
            thongKeBaiThiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeBaiThiPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thongKeBaiThiLB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        luaChonThongKe1.add(thongKeBaiThiPanel);

        chonThongKePanel.add(luaChonThongKe1);

        luaChonThongKe2.setBackground(new java.awt.Color(255, 255, 255));
        luaChonThongKe2.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        thongKeSoSanhPanel.setBackground(new java.awt.Color(153, 255, 255));
        thongKeSoSanhPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        thongKeSoSanhPanel.setPreferredSize(new java.awt.Dimension(350, 205));
        thongKeSoSanhPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKeSoSanhPanelMouseClicked(evt);
            }
        });

        thongKeSoSanhLB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thongKeSoSanhLB.setForeground(new java.awt.Color(0, 0, 0));
        thongKeSoSanhLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongKeSoSanhLB.setText("So Sánh Kết Quả");

        javax.swing.GroupLayout thongKeSoSanhPanelLayout = new javax.swing.GroupLayout(thongKeSoSanhPanel);
        thongKeSoSanhPanel.setLayout(thongKeSoSanhPanelLayout);
        thongKeSoSanhPanelLayout.setHorizontalGroup(
            thongKeSoSanhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeSoSanhPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thongKeSoSanhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(thongKeSoSanhLB, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addContainerGap())
        );
        thongKeSoSanhPanelLayout.setVerticalGroup(
            thongKeSoSanhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeSoSanhPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thongKeSoSanhLB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        luaChonThongKe2.add(thongKeSoSanhPanel);

        thongKeLichSuPanel.setBackground(new java.awt.Color(153, 153, 255));
        thongKeLichSuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        thongKeLichSuPanel.setPreferredSize(new java.awt.Dimension(350, 205));
        thongKeLichSuPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKeLichSuPanelMouseClicked(evt);
            }
        });

        thongKeLichSuLB.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thongKeLichSuLB.setForeground(new java.awt.Color(0, 0, 0));
        thongKeLichSuLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongKeLichSuLB.setText("Lịch Sử Bài Thi");

        javax.swing.GroupLayout thongKeLichSuPanelLayout = new javax.swing.GroupLayout(thongKeLichSuPanel);
        thongKeLichSuPanel.setLayout(thongKeLichSuPanelLayout);
        thongKeLichSuPanelLayout.setHorizontalGroup(
            thongKeLichSuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeLichSuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thongKeLichSuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(thongKeLichSuLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addContainerGap())
        );
        thongKeLichSuPanelLayout.setVerticalGroup(
            thongKeLichSuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeLichSuPanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thongKeLichSuLB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        luaChonThongKe2.add(thongKeLichSuPanel);

        chonThongKePanel.add(luaChonThongKe2);

        add(chonThongKePanel);

        hienThiThongKePanel.setBackground(new java.awt.Color(255, 255, 153));
        hienThiThongKePanel.setLayout(new java.awt.CardLayout());

        thongKeBaiThiCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        thongKeBaiThiCardPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        thongKeBaiThiCardPanel.setLayout(new java.awt.BorderLayout(5, 10));

        thongKeBaiThiCardLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        thongKeBaiThiCardLB.setForeground(new java.awt.Color(0, 0, 0));
        thongKeBaiThiCardLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongKeBaiThiCardLB.setText("Thống Kê Bài Thi");
        thongKeBaiThiCardLB.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        thongKeBaiThiCardLB.setPreferredSize(new java.awt.Dimension(200, 40));
        thongKeBaiThiCardPanel.add(thongKeBaiThiCardLB, java.awt.BorderLayout.PAGE_START);

        thongKeBaiThiCardPN.setBackground(new java.awt.Color(255, 255, 255));
        thongKeBaiThiCardPN.setLayout(new java.awt.BorderLayout(0, 10));

        progressThongKeBaiThiCardPN.setBackground(new java.awt.Color(153, 255, 153));
        progressThongKeBaiThiCardPN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        progressThongKeBaiThiCardPN.setPreferredSize(new java.awt.Dimension(509, 150));
        progressThongKeBaiThiCardPN.setLayout(new java.awt.BorderLayout(10, 0));

        scoreThongKeBaiThiPN.setBackground(new java.awt.Color(255, 255, 255));
        scoreThongKeBaiThiPN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        scoreThongKeBaiThiPN.setPreferredSize(new java.awt.Dimension(180, 465));
        scoreThongKeBaiThiPN.setLayout(new java.awt.GridLayout(4, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Score");
        jPanel6.add(jLabel9);

        scoreThongKeBaiThiPN.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        JLabel10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        JLabel10.setForeground(new java.awt.Color(51, 153, 0));
        JLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel10.setText("High Score");
        jPanel7.add(JLabel10, java.awt.BorderLayout.PAGE_END);

        highScoreThongKeBaiThiLB.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        highScoreThongKeBaiThiLB.setForeground(new java.awt.Color(0, 0, 0));
        highScoreThongKeBaiThiLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScoreThongKeBaiThiLB.setText("100");
        jPanel7.add(highScoreThongKeBaiThiLB, java.awt.BorderLayout.CENTER);

        scoreThongKeBaiThiPN.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Low Score");
        jPanel8.add(jLabel12, java.awt.BorderLayout.PAGE_END);

        lowScoreThongKeBaiThiLB.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lowScoreThongKeBaiThiLB.setForeground(new java.awt.Color(0, 0, 0));
        lowScoreThongKeBaiThiLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lowScoreThongKeBaiThiLB.setText("50");
        jPanel8.add(lowScoreThongKeBaiThiLB, java.awt.BorderLayout.CENTER);

        scoreThongKeBaiThiPN.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 153, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Target");
        jPanel9.add(jLabel14, java.awt.BorderLayout.PAGE_END);

        targetThongKeBaiThiLB.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        targetThongKeBaiThiLB.setForeground(new java.awt.Color(0, 0, 0));
        targetThongKeBaiThiLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        targetThongKeBaiThiLB.setText("Đạt");
        jPanel9.add(targetThongKeBaiThiLB, java.awt.BorderLayout.CENTER);

        scoreThongKeBaiThiPN.add(jPanel9);

        progressThongKeBaiThiCardPN.add(scoreThongKeBaiThiPN, java.awt.BorderLayout.LINE_END);

        progressThongKeBaiThiPN.setBackground(new java.awt.Color(255, 255, 255));
        progressThongKeBaiThiPN.setLayout(new java.awt.GridLayout(8, 0));

        cauTraLoiDungThongKeBaiThiLB.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        cauTraLoiDungThongKeBaiThiLB.setForeground(new java.awt.Color(0, 0, 0));
        cauTraLoiDungThongKeBaiThiLB.setText("Câu trả lời đúng");
        progressThongKeBaiThiPN.add(cauTraLoiDungThongKeBaiThiLB);
        progressThongKeBaiThiPN.add(cauTraLoiDungTKBaiThiPB);

        jLabel11.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Câu trả lời sai");
        progressThongKeBaiThiPN.add(jLabel11);
        progressThongKeBaiThiPN.add(cauTraLoiSaiTKBaiThiPB);

        jLabel13.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Thời gian làm bài");
        progressThongKeBaiThiPN.add(jLabel13);
        progressThongKeBaiThiPN.add(thoiGianLamBaiTKBaiPB);

        jLabel15.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Thi lại");
        progressThongKeBaiThiPN.add(jLabel15);
        progressThongKeBaiThiPN.add(thiLaiTKBaiThiPB);

        progressThongKeBaiThiCardPN.add(progressThongKeBaiThiPN, java.awt.BorderLayout.CENTER);

        thongKeBaiThiCardPN.add(progressThongKeBaiThiCardPN, java.awt.BorderLayout.CENTER);

        searchThongKeBaiThiCardPN.setBackground(new java.awt.Color(153, 255, 153));
        searchThongKeBaiThiCardPN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        searchThongKeBaiThiCardPN.setPreferredSize(new java.awt.Dimension(509, 170));
        searchThongKeBaiThiCardPN.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jLabel7.setBackground(new java.awt.Color(153, 255, 153));
        jLabel7.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Topic:");
        jPanel3.add(jLabel7);

        topicSearchComboBox.setBackground(new java.awt.Color(255, 255, 255));
        topicSearchComboBox.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        topicSearchComboBox.setForeground(new java.awt.Color(0, 0, 0));
        topicSearchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(topicSearchComboBox);

        searchThongKeBaiThiCardPN.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        topicSearchTF.setBackground(new java.awt.Color(255, 255, 255));
        topicSearchTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        topicSearchTF.setForeground(new java.awt.Color(0, 0, 0));
        topicSearchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicSearchTFActionPerformed(evt);
            }
        });
        jPanel2.add(topicSearchTF);

        searchThongKeBaiThiCardPN.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Exam:");
        jPanel4.add(jLabel8);

        searchThongKeBaiThiCardPN.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        examSearchTF.setBackground(new java.awt.Color(255, 255, 255));
        examSearchTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        examSearchTF.setForeground(new java.awt.Color(0, 0, 0));
        examSearchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examSearchTFActionPerformed(evt);
            }
        });
        jPanel5.add(examSearchTF);

        searchThongKeBaiThiCardPN.add(jPanel5);

        thongKeBaiThiCardPN.add(searchThongKeBaiThiCardPN, java.awt.BorderLayout.PAGE_START);

        thongKeBaiThiCardPanel.add(thongKeBaiThiCardPN, java.awt.BorderLayout.CENTER);

        jLabel16.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Lời Nhắc: ");
        jLabel16.setPreferredSize(new java.awt.Dimension(72, 50));
        thongKeBaiThiCardPanel.add(jLabel16, java.awt.BorderLayout.PAGE_END);

        hienThiThongKePanel.add(thongKeBaiThiCardPanel, "card3");

        thongKeSoSanhCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        thongKeSoSanhCardPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        thongKeSoSanhCardPanel.setLayout(new java.awt.BorderLayout(5, 10));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("So Sánh Kết Quả");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        jLabel10.setPreferredSize(new java.awt.Dimension(59, 40));
        thongKeSoSanhCardPanel.add(jLabel10, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        searchSoSanhKetQuaPN.setBackground(new java.awt.Color(204, 255, 255));
        searchSoSanhKetQuaPN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        searchSoSanhKetQuaPN.setLayout(new java.awt.BorderLayout(10, 2));

        jLabel17.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Search");
        jLabel17.setPreferredSize(new java.awt.Dimension(59, 30));
        searchSoSanhKetQuaPN.add(jLabel17, java.awt.BorderLayout.PAGE_START);

        jPanel14.setBackground(new java.awt.Color(204, 255, 255));
        jPanel14.setLayout(new java.awt.GridLayout(3, 0));

        jLabel19.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Topic:");
        jPanel14.add(jLabel19);

        searchTopicSoSanhKetQuaTF.setBackground(new java.awt.Color(255, 255, 255));
        searchTopicSoSanhKetQuaTF.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel14.add(searchTopicSoSanhKetQuaTF);

        searchTopicSoSanhKetQuaCB.setBackground(new java.awt.Color(204, 204, 204));
        searchTopicSoSanhKetQuaCB.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        searchTopicSoSanhKetQuaCB.setForeground(new java.awt.Color(0, 0, 0));
        searchTopicSoSanhKetQuaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(searchTopicSoSanhKetQuaCB);

        jLabel20.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Exam:");
        jPanel14.add(jLabel20);

        searchExamSoSanhKetQuaTF.setBackground(new java.awt.Color(255, 255, 255));
        searchExamSoSanhKetQuaTF.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel14.add(searchExamSoSanhKetQuaTF);

        searchExamSoSanhKetQuaCB.setBackground(new java.awt.Color(204, 204, 204));
        searchExamSoSanhKetQuaCB.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        searchExamSoSanhKetQuaCB.setForeground(new java.awt.Color(0, 0, 0));
        searchExamSoSanhKetQuaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(searchExamSoSanhKetQuaCB);

        jLabel21.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("User:");
        jPanel14.add(jLabel21);

        searchUserSoSanhKetQuaTF.setBackground(new java.awt.Color(255, 255, 255));
        searchUserSoSanhKetQuaTF.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel14.add(searchUserSoSanhKetQuaTF);

        searchUserSoSanhKetQuaCB.setBackground(new java.awt.Color(204, 204, 204));
        searchUserSoSanhKetQuaCB.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        searchUserSoSanhKetQuaCB.setForeground(new java.awt.Color(0, 0, 0));
        searchUserSoSanhKetQuaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(searchUserSoSanhKetQuaCB);

        searchSoSanhKetQuaPN.add(jPanel14, java.awt.BorderLayout.CENTER);

        ketQuaTimKiemSoSanhKetQuaLB.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        ketQuaTimKiemSoSanhKetQuaLB.setForeground(new java.awt.Color(0, 0, 0));
        ketQuaTimKiemSoSanhKetQuaLB.setText("Thông báo kết quả tìm kiếm: ");
        ketQuaTimKiemSoSanhKetQuaLB.setPreferredSize(new java.awt.Dimension(59, 30));
        searchSoSanhKetQuaPN.add(ketQuaTimKiemSoSanhKetQuaLB, java.awt.BorderLayout.PAGE_END);

        jPanel10.add(searchSoSanhKetQuaPN);

        ketQuaUser1PN.setBackground(new java.awt.Color(204, 255, 255));
        ketQuaUser1PN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        ketQuaUser1PN.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel18.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("KẾT QUẢ USER 1:");
        jLabel18.setPreferredSize(new java.awt.Dimension(157, 30));
        ketQuaUser1PN.add(jLabel18, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new java.awt.GridLayout(6, 0));

        jLabel23.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Số Câu Đúng:");
        jPanel12.add(jLabel23);

        soCauDungUser1PB.setBackground(new java.awt.Color(204, 204, 204));
        soCauDungUser1PB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        soCauDungUser1PB.setForeground(new java.awt.Color(204, 255, 255));
        jPanel12.add(soCauDungUser1PB);

        jLabel24.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Số Câu Sai:");
        jPanel12.add(jLabel24);

        soCauTraLoiSaiUser1PB.setBackground(new java.awt.Color(204, 204, 204));
        soCauTraLoiSaiUser1PB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        soCauTraLoiSaiUser1PB.setForeground(new java.awt.Color(204, 255, 255));
        jPanel12.add(soCauTraLoiSaiUser1PB);

        jLabel28.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Thời Gian Hoàn Thành:");
        jPanel12.add(jLabel28);

        thoiGianHTUser1PB.setBackground(new java.awt.Color(204, 204, 204));
        thoiGianHTUser1PB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thoiGianHTUser1PB.setForeground(new java.awt.Color(204, 255, 255));
        jPanel12.add(thoiGianHTUser1PB);

        jPanel11.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel29.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 153));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("High Score");
        jLabel29.setPreferredSize(new java.awt.Dimension(95, 40));
        jPanel13.add(jLabel29, java.awt.BorderLayout.PAGE_END);

        highScoreUser1LB.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        highScoreUser1LB.setForeground(new java.awt.Color(0, 0, 0));
        highScoreUser1LB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScoreUser1LB.setText("100");
        jPanel13.add(highScoreUser1LB, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel13);

        ketQuaUser1PN.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel10.add(ketQuaUser1PN);

        ketQuaUser2PN.setBackground(new java.awt.Color(204, 255, 255));
        ketQuaUser2PN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        ketQuaUser2PN.setLayout(new java.awt.BorderLayout());

        jLabel30.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("KẾT QUẢ USER 2:");
        jLabel30.setPreferredSize(new java.awt.Dimension(157, 30));
        ketQuaUser2PN.add(jLabel30, java.awt.BorderLayout.PAGE_START);

        jPanel15.setBackground(new java.awt.Color(204, 255, 255));
        jPanel15.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0)));
        jPanel17.setLayout(new java.awt.GridLayout(6, 0));

        jLabel34.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Số Câu Đúng:");
        jPanel17.add(jLabel34);

        soCauDungUser2PB.setBackground(new java.awt.Color(204, 204, 204));
        soCauDungUser2PB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        soCauDungUser2PB.setForeground(new java.awt.Color(204, 255, 255));
        jPanel17.add(soCauDungUser2PB);

        jLabel35.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Số Câu Sai:");
        jPanel17.add(jLabel35);

        soCauTraLoiSaiUser2PB.setBackground(new java.awt.Color(204, 204, 204));
        soCauTraLoiSaiUser2PB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        soCauTraLoiSaiUser2PB.setForeground(new java.awt.Color(204, 255, 255));
        jPanel17.add(soCauTraLoiSaiUser2PB);

        jLabel36.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Thời Gian Hoàn Thành:");
        jPanel17.add(jLabel36);

        thoiGianHTUser2PB.setBackground(new java.awt.Color(204, 204, 204));
        thoiGianHTUser2PB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thoiGianHTUser2PB.setForeground(new java.awt.Color(204, 255, 255));
        jPanel17.add(thoiGianHTUser2PB);

        jPanel15.add(jPanel17);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel38.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 153, 153));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("High Score");
        jLabel38.setPreferredSize(new java.awt.Dimension(95, 40));
        jPanel20.add(jLabel38, java.awt.BorderLayout.PAGE_END);

        highScoreUser2LB.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        highScoreUser2LB.setForeground(new java.awt.Color(0, 0, 0));
        highScoreUser2LB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScoreUser2LB.setText("100");
        jPanel20.add(highScoreUser2LB, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel20);

        ketQuaUser2PN.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel10.add(ketQuaUser2PN);

        thongKeSoSanhCardPanel.add(jPanel10, java.awt.BorderLayout.CENTER);

        hienThiThongKePanel.add(thongKeSoSanhCardPanel, "card4");

        thongKeLichSuCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        thongKeLichSuCardPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204)));
        thongKeLichSuCardPanel.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel39.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Lịch Sử Bài Thi");
        jLabel39.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0)));
        thongKeLichSuCardPanel.add(jLabel39, java.awt.BorderLayout.PAGE_START);

        lichSuBaiThiPN.setBackground(new java.awt.Color(255, 255, 255));
        lichSuBaiThiPN.setLayout(new java.awt.GridLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        lichSuBaiThiPN.add(jScrollPane1);

        thongKeLichSuCardPanel.add(lichSuBaiThiPN, java.awt.BorderLayout.CENTER);

        hienThiThongKePanel.add(thongKeLichSuCardPanel, "card5");

        thongKeTongCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        thongKeTongCardPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));
        thongKeTongCardPanel.setLayout(new java.awt.BorderLayout(10, 20));

        tieuDeThongKeTongPN.setBackground(new java.awt.Color(255, 255, 255));
        tieuDeThongKeTongPN.setPreferredSize(new java.awt.Dimension(509, 150));
        tieuDeThongKeTongPN.setLayout(new java.awt.BorderLayout(0, 10));

        thongKeTongCardLB.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        thongKeTongCardLB.setForeground(new java.awt.Color(0, 0, 0));
        thongKeTongCardLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongKeTongCardLB.setText("Thống Kê Tổng");
        thongKeTongCardLB.setToolTipText("");
        thongKeTongCardLB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        thongKeTongCardLB.setPreferredSize(new java.awt.Dimension(175, 40));
        tieuDeThongKeTongPN.add(thongKeTongCardLB, java.awt.BorderLayout.PAGE_START);

        searchThongKeTongPN.setBackground(new java.awt.Color(255, 102, 102));
        searchThongKeTongPN.setLayout(new java.awt.BorderLayout(5, 0));

        searchTopicAndExamTKTongPN.setBackground(new java.awt.Color(255, 153, 153));
        searchTopicAndExamTKTongPN.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        searchTopicAndExamTKTongPN.setLayout(new java.awt.GridLayout(4, 0));

        jLabel25.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Topic");
        searchTopicAndExamTKTongPN.add(jLabel25);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new java.awt.BorderLayout());

        searchTopicTKTongCB.setBackground(new java.awt.Color(204, 204, 204));
        searchTopicTKTongCB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchTopicTKTongCB.setForeground(new java.awt.Color(0, 0, 0));
        searchTopicTKTongCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchTopicTKTongCB.setPreferredSize(new java.awt.Dimension(200, 28));
        searchTopicTKTongCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTopicTKTongCBActionPerformed(evt);
            }
        });
        jPanel16.add(searchTopicTKTongCB, java.awt.BorderLayout.LINE_END);

        searchTopicTKTongTF.setBackground(new java.awt.Color(255, 255, 255));
        searchTopicTKTongTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchTopicTKTongTF.setForeground(new java.awt.Color(0, 0, 0));
        jPanel16.add(searchTopicTKTongTF, java.awt.BorderLayout.CENTER);

        searchTopicAndExamTKTongPN.add(jPanel16);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Exam");
        searchTopicAndExamTKTongPN.add(jLabel26);

        searchExamTKTongTF.setBackground(new java.awt.Color(255, 255, 255));
        searchExamTKTongTF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchExamTKTongTF.setForeground(new java.awt.Color(0, 0, 0));
        searchTopicAndExamTKTongPN.add(searchExamTKTongTF);

        searchThongKeTongPN.add(searchTopicAndExamTKTongPN, java.awt.BorderLayout.CENTER);

        tieuDeThongKeTongPN.add(searchThongKeTongPN, java.awt.BorderLayout.CENTER);

        thongKeTongCardPanel.add(tieuDeThongKeTongPN, java.awt.BorderLayout.PAGE_START);

        thongKeTongScorePanel.setBackground(new java.awt.Color(255, 255, 255));
        thongKeTongScorePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        thongKeTongScorePanel.setPreferredSize(new java.awt.Dimension(200, 631));
        thongKeTongScorePanel.setVerifyInputWhenFocusTarget(false);
        thongKeTongScorePanel.setLayout(new java.awt.GridLayout(4, 0));

        scoreLB.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        scoreLB.setForeground(new java.awt.Color(204, 0, 51));
        scoreLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreLB.setText("SCORE");
        scoreLB.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        thongKeTongScorePanel.add(scoreLB);

        highScorePN.setBackground(new java.awt.Color(255, 255, 255));
        highScorePN.setLayout(new java.awt.BorderLayout());

        highScoreLB.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        highScoreLB.setForeground(new java.awt.Color(255, 102, 102));
        highScoreLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScoreLB.setText("High Score");
        highScoreLB.setPreferredSize(new java.awt.Dimension(127, 40));
        highScorePN.add(highScoreLB, java.awt.BorderLayout.PAGE_END);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("40");
        highScorePN.add(jLabel3, java.awt.BorderLayout.CENTER);

        thongKeTongScorePanel.add(highScorePN);

        lowScorePN.setBackground(new java.awt.Color(255, 255, 255));
        lowScorePN.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Low Score");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 40));
        lowScorePN.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("20");
        lowScorePN.add(jLabel4, java.awt.BorderLayout.CENTER);

        thongKeTongScorePanel.add(lowScorePN);

        averageScorePN.setBackground(new java.awt.Color(255, 255, 255));
        averageScorePN.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Average Score");
        averageScorePN.add(jLabel5, java.awt.BorderLayout.PAGE_END);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("50");
        averageScorePN.add(jLabel6, java.awt.BorderLayout.CENTER);

        thongKeTongScorePanel.add(averageScorePN);

        thongKeTongCardPanel.add(thongKeTongScorePanel, java.awt.BorderLayout.LINE_END);

        thongKeTongProgressPanel.setBackground(new java.awt.Color(255, 255, 255));
        thongKeTongProgressPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        thongKeTongProgressPanel.setLayout(new java.awt.GridLayout(12, 0));

        tBThoiGianHoanThanhLB.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        tBThoiGianHoanThanhLB.setForeground(new java.awt.Color(0, 0, 0));
        tBThoiGianHoanThanhLB.setText("Trung Bình Thời Gian Hoàn Thành Đề Thi");
        thongKeTongProgressPanel.add(tBThoiGianHoanThanhLB);

        tBThoiGianHoanThanhPB.setBackground(new java.awt.Color(204, 204, 204));
        tBThoiGianHoanThanhPB.setForeground(new java.awt.Color(255, 153, 153));
        thongKeTongProgressPanel.add(tBThoiGianHoanThanhPB);

        tBSoLanThiLaiLB.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        tBSoLanThiLaiLB.setForeground(new java.awt.Color(0, 0, 0));
        tBSoLanThiLaiLB.setText("Trung Bình Số Lần Thi Lại ");
        thongKeTongProgressPanel.add(tBSoLanThiLaiLB);

        tBSoLanThiLaiPB.setBackground(new java.awt.Color(204, 204, 204));
        tBSoLanThiLaiPB.setForeground(new java.awt.Color(255, 153, 153));
        thongKeTongProgressPanel.add(tBSoLanThiLaiPB);

        tBCauTraLoiDungLB.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        tBCauTraLoiDungLB.setForeground(new java.awt.Color(0, 0, 0));
        tBCauTraLoiDungLB.setText("Trung Bình Câu Trả Lời Đúng");
        thongKeTongProgressPanel.add(tBCauTraLoiDungLB);

        tBCauTraLoiDungPB.setBackground(new java.awt.Color(204, 204, 204));
        tBCauTraLoiDungPB.setForeground(new java.awt.Color(255, 153, 153));
        thongKeTongProgressPanel.add(tBCauTraLoiDungPB);

        tBCauTraLoiSaiLB.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        tBCauTraLoiSaiLB.setForeground(new java.awt.Color(0, 0, 0));
        tBCauTraLoiSaiLB.setText("Trung Bình Câu Trả Lời Sai");
        thongKeTongProgressPanel.add(tBCauTraLoiSaiLB);

        jProgressBar5.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBar5.setForeground(new java.awt.Color(255, 153, 153));
        thongKeTongProgressPanel.add(jProgressBar5);

        pTHoanThanhDeThiLB.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        pTHoanThanhDeThiLB.setForeground(new java.awt.Color(0, 0, 0));
        pTHoanThanhDeThiLB.setText("Phần Trăm Hoàn Thành Đề Thi");
        thongKeTongProgressPanel.add(pTHoanThanhDeThiLB);

        pTHoanThanhDeThiPB.setBackground(new java.awt.Color(204, 204, 204));
        pTHoanThanhDeThiPB.setForeground(new java.awt.Color(255, 153, 153));
        thongKeTongProgressPanel.add(pTHoanThanhDeThiPB);

        pTKhongHoanThanhDeThiLB.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        pTKhongHoanThanhDeThiLB.setForeground(new java.awt.Color(0, 0, 0));
        pTKhongHoanThanhDeThiLB.setText("Phần Trăm Không Hoàn Thành Đề Thi");
        thongKeTongProgressPanel.add(pTKhongHoanThanhDeThiLB);

        pTKhongHoanThanhDeThiPB.setBackground(new java.awt.Color(204, 204, 204));
        pTKhongHoanThanhDeThiPB.setForeground(new java.awt.Color(255, 153, 153));
        pTKhongHoanThanhDeThiPB.setToolTipText("\n\n");
        pTKhongHoanThanhDeThiPB.setValue(50);
        pTKhongHoanThanhDeThiPB.setName(""); // NOI18N
        thongKeTongProgressPanel.add(pTKhongHoanThanhDeThiPB);

        thongKeTongCardPanel.add(thongKeTongProgressPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tiến Độ Học Tập Trung Bình Của Các Thành Viên: ĐẠT");
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        thongKeTongCardPanel.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        hienThiThongKePanel.add(thongKeTongCardPanel, "card2");

        add(hienThiThongKePanel);
    }// </editor-fold>//GEN-END:initComponents

    private void thongKeTongPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeTongPanelMouseClicked
        // Mo card tuong ung
        cardLayout.show(hienThiThongKePanel, thongKeTongLB.getText());
    }//GEN-LAST:event_thongKeTongPanelMouseClicked

    private void thongKeBaiThiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeBaiThiPanelMouseClicked
        // Mo card tuong ung
        cardLayout.show(hienThiThongKePanel, thongKeBaiThiLB.getText());
    }//GEN-LAST:event_thongKeBaiThiPanelMouseClicked

    private void examSearchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examSearchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examSearchTFActionPerformed

    private void searchTopicTKTongCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTopicTKTongCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTopicTKTongCBActionPerformed

    private void topicSearchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicSearchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicSearchTFActionPerformed

    private void searchUserThongKeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserThongKeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchUserThongKeTFActionPerformed

    private void thongKeSoSanhPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeSoSanhPanelMouseClicked
        cardLayout.show(hienThiThongKePanel, thongKeSoSanhLB.getText());
    }//GEN-LAST:event_thongKeSoSanhPanelMouseClicked

    private void thongKeLichSuPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeLichSuPanelMouseClicked
        cardLayout.show(hienThiThongKePanel, thongKeLichSuLB.getText());
    }//GEN-LAST:event_thongKeLichSuPanelMouseClicked

    
    public void initCartForThongKe() {
        thongKeTongCardPanel.setBackground(Color.white);
        thongKeBaiThiCardPanel.setBackground(Color.white);
        thongKeSoSanhCardPanel.setBackground(Color.white);
        thongKeLichSuCardPanel.setBackground(Color.white);
        hienThiThongKePanel.setLayout(cardLayout);
        hienThiThongKePanel.add(thongKeTongCardPanel, thongKeTongLB.getText());
        hienThiThongKePanel.add(thongKeBaiThiCardPanel, thongKeBaiThiLB.getText());
        hienThiThongKePanel.add(thongKeSoSanhCardPanel, thongKeSoSanhLB.getText());
        hienThiThongKePanel.add(thongKeLichSuCardPanel, thongKeLichSuLB.getText());
    } 
            
            
//    public static void main(String[] args) {
//        JFrame frame = new JFrame();
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setSize(1200, 800);
//        frame.add(new MainThongKePanel());
//        frame.setVisible(true);
//    }
    
    private CardLayout cardLayout = new CardLayout();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel10;
    private javax.swing.JPanel averageScorePN;
    private javax.swing.JProgressBar cauTraLoiDungTKBaiThiPB;
    private javax.swing.JLabel cauTraLoiDungThongKeBaiThiLB;
    private javax.swing.JProgressBar cauTraLoiSaiTKBaiThiPB;
    private javax.swing.JPanel chonThongKePanel;
    private javax.swing.JLabel emailThongKeLB;
    private javax.swing.JTextField examSearchTF;
    private javax.swing.JLabel fullNameThongKeLB;
    private javax.swing.JPanel hienThiThongKePanel;
    private javax.swing.JLabel highScoreLB;
    private javax.swing.JPanel highScorePN;
    private javax.swing.JLabel highScoreThongKeBaiThiLB;
    private javax.swing.JLabel highScoreUser1LB;
    private javax.swing.JLabel highScoreUser2LB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel ketQuaTimKiemSoSanhKetQuaLB;
    private javax.swing.JPanel ketQuaUser1PN;
    private javax.swing.JPanel ketQuaUser2PN;
    private javax.swing.JPanel lichSuBaiThiPN;
    private javax.swing.JPanel lowScorePN;
    private javax.swing.JLabel lowScoreThongKeBaiThiLB;
    private javax.swing.JPanel luaChonThongKe1;
    private javax.swing.JPanel luaChonThongKe2;
    private javax.swing.JLabel pTHoanThanhDeThiLB;
    private javax.swing.JProgressBar pTHoanThanhDeThiPB;
    private javax.swing.JLabel pTKhongHoanThanhDeThiLB;
    private javax.swing.JProgressBar pTKhongHoanThanhDeThiPB;
    private javax.swing.JPanel progressThongKeBaiThiCardPN;
    private javax.swing.JPanel progressThongKeBaiThiPN;
    private javax.swing.JLabel scoreLB;
    private javax.swing.JPanel scoreThongKeBaiThiPN;
    private javax.swing.JComboBox<String> searchExamSoSanhKetQuaCB;
    private javax.swing.JTextField searchExamSoSanhKetQuaTF;
    private javax.swing.JTextField searchExamTKTongTF;
    private javax.swing.JPanel searchSoSanhKetQuaPN;
    private javax.swing.JPanel searchThongKeBaiThiCardPN;
    private javax.swing.JPanel searchThongKeTongPN;
    private javax.swing.JPanel searchTopicAndExamTKTongPN;
    private javax.swing.JComboBox<String> searchTopicSoSanhKetQuaCB;
    private javax.swing.JTextField searchTopicSoSanhKetQuaTF;
    private javax.swing.JComboBox<String> searchTopicTKTongCB;
    private javax.swing.JTextField searchTopicTKTongTF;
    private javax.swing.JPanel searchUserPN;
    private javax.swing.JComboBox<String> searchUserSoSanhKetQuaCB;
    private javax.swing.JTextField searchUserSoSanhKetQuaTF;
    private javax.swing.JComboBox<String> searchUserThongKeCB;
    private javax.swing.JTextField searchUserThongKeTF;
    private javax.swing.JProgressBar soCauDungUser1PB;
    private javax.swing.JProgressBar soCauDungUser2PB;
    private javax.swing.JProgressBar soCauTraLoiSaiUser1PB;
    private javax.swing.JProgressBar soCauTraLoiSaiUser2PB;
    private javax.swing.JLabel tBCauTraLoiDungLB;
    private javax.swing.JProgressBar tBCauTraLoiDungPB;
    private javax.swing.JLabel tBCauTraLoiSaiLB;
    private javax.swing.JLabel tBSoLanThiLaiLB;
    private javax.swing.JProgressBar tBSoLanThiLaiPB;
    private javax.swing.JLabel tBThoiGianHoanThanhLB;
    private javax.swing.JProgressBar tBThoiGianHoanThanhPB;
    private javax.swing.JLabel targetThongKeBaiThiLB;
    private javax.swing.JProgressBar thiLaiTKBaiThiPB;
    private javax.swing.JProgressBar thoiGianHTUser1PB;
    private javax.swing.JProgressBar thoiGianHTUser2PB;
    private javax.swing.JProgressBar thoiGianLamBaiTKBaiPB;
    private javax.swing.JLabel thongKeBaiThiCardLB;
    private javax.swing.JPanel thongKeBaiThiCardPN;
    private javax.swing.JPanel thongKeBaiThiCardPanel;
    private javax.swing.JLabel thongKeBaiThiLB;
    private javax.swing.JPanel thongKeBaiThiPanel;
    private javax.swing.JPanel thongKeLichSuCardPanel;
    private javax.swing.JLabel thongKeLichSuLB;
    private javax.swing.JPanel thongKeLichSuPanel;
    private javax.swing.JPanel thongKeSoSanhCardPanel;
    private javax.swing.JLabel thongKeSoSanhLB;
    private javax.swing.JPanel thongKeSoSanhPanel;
    private javax.swing.JLabel thongKeTongCardLB;
    private javax.swing.JPanel thongKeTongCardPanel;
    private javax.swing.JLabel thongKeTongLB;
    private javax.swing.JPanel thongKeTongPanel;
    private javax.swing.JPanel thongKeTongProgressPanel;
    private javax.swing.JPanel thongKeTongScorePanel;
    private javax.swing.JPanel thongTinUserThongKePN;
    private javax.swing.JPanel tieuDePN;
    private javax.swing.JPanel tieuDeThongKePN;
    private javax.swing.JPanel tieuDeThongKeTongPN;
    private javax.swing.JComboBox<String> topicSearchComboBox;
    private javax.swing.JTextField topicSearchTF;
    private javax.swing.JLabel userIdThongKeLB;
    private javax.swing.JLabel userNameThongKeLB;
    // End of variables declaration//GEN-END:variables
}
