/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.qlthitracnghiem.GUI.Info;

import java.util.Date;

/**
 *
 * @author truon
 */
public class ExamResultPanel extends javax.swing.JPanel {

    public ExamResultPanel() {
        initComponents();
    }

    // rs_num, exCode, title, rs_mark, rs_date, topic
    public ExamResultPanel(String[] propValues) {
        initComponents();
        txtResultNum.setText("Lần thi: " + Integer.parseInt(propValues[0]));
        txtExCode.setText("Mã đề thi: " + propValues[1]);
        txtTitle.setText(propValues[2]);
        txtMark.setText(propValues[3]);
        txtDate.setText("Ngày thi: " + propValues[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtTitle = new javax.swing.JLabel();
        txtResultNum = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        txtMark = new javax.swing.JLabel();
        txtExCode = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setForeground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000000, 116));
        setPreferredSize(new java.awt.Dimension(465, 116));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] { 0, 8, 0, 8, 0, 8, 0 };
        layout.rowHeights = new int[] { 0, 5, 0, 5, 0 };
        setLayout(layout);

        txtTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtTitle.setText("Kiểm tra giữ kì");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        add(txtTitle, gridBagConstraints);

        txtResultNum.setText("Lần thi: 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.1;
        add(txtResultNum, gridBagConstraints);

        txtDate.setText("Ngày thi: 01/01/2001");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        add(txtDate, gridBagConstraints);

        txtMark.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMark.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMark.setText("9.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        add(txtMark, gridBagConstraints);

        txtExCode.setText("Mã đề thi: TST001A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(txtExCode, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtExCode;
    private javax.swing.JLabel txtMark;
    private javax.swing.JLabel txtResultNum;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
