/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.qlthitracnghiem.GUI.CauHoi;

import com.example.qlthitracnghiem.BUS.QuestionsBUS;
import com.example.qlthitracnghiem.BUS.TopicsBUS;
import com.example.qlthitracnghiem.DAO.TopicsDAO;
import com.example.qlthitracnghiem.DTO.QuestionsDTO;
import com.example.qlthitracnghiem.DTO.TopicsDTO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author truon
 */
public class QuestionPanel extends javax.swing.JPanel {

    public TopicsBUS topicsBUS = new TopicsBUS();
    /**
     * Creates new form QuestionPanel
     */
    public QuestionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        btnSuaChuDe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        btnThemChuDe = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_question = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1040, 700));

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton5.setText("Xóa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnSuaChuDe.setText("Sửa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Chủ đề");

        jScrollPane3.setViewportView(jTree2);
        loadTopics();

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnThemChuDe.setText("Thêm");
        btnThemChuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChuDeActionPerformed(evt);
            }
        });

        Reset.setText("Tải lại");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        // Thêm style cho nút
        Reset.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14)); // Chữ đậm, cỡ 14
        Reset.setBackground(new java.awt.Color(255, 102, 102)); // Màu nền đỏ nhạt
        Reset.setForeground(Color.WHITE); // Chữ trắng
        Reset.setFocusPainted(false); // Bỏ viền khi nhấn
        Reset.setBorder(BorderFactory.createEtchedBorder()); // Viền nổi nhẹ
        Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR)); // Đổi con trỏ chuột khi di vào

        // Thêm hiệu ứng hover
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Reset.setBackground(new java.awt.Color(255, 51, 51)); // Đỏ đậm hơn khi hover
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Reset.setBackground(new java.awt.Color(255, 102, 102)); // Quay lại màu cũ
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnThemChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSuaChuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Reset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(btnThemChuDe))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSuaChuDe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        // Thay đổi màu nền và màu chữ cho nút bình thường
        jButton5.setBackground(new java.awt.Color(255, 69, 0));  // Màu nền đỏ cam (RGB: 255, 69, 0)
        jButton5.setForeground(new java.awt.Color(255, 255, 255));  // Màu chữ trắng

        // Thay đổi font chữ
        jButton5.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));

        // Tạo hiệu ứng khi chuột di chuyển qua nút (hover)
        jButton5.setRolloverEnabled(true);  // Kích hoạt hiệu ứng khi di chuột qua nút

        // Khi hover, thay đổi màu nền của nút
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5.setBackground(new java.awt.Color(255, 99, 71));  // Màu nền đỏ sáng khi hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5.setBackground(new java.awt.Color(255, 69, 0));  // Trở lại màu đỏ cam khi không hover
            }
        });
        // Thay đổi màu nền và màu chữ cho nút bình thường
        btnSuaChuDe.setBackground(new java.awt.Color(50, 205, 50));  // Màu nền xanh lá (RGB: 50, 205, 50)
        btnSuaChuDe.setForeground(new java.awt.Color(255, 255, 255));  // Màu chữ trắng

        // Thay đổi font chữ
        btnSuaChuDe.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));

        // Tạo hiệu ứng khi chuột di chuyển qua nút (hover)
        btnSuaChuDe.setRolloverEnabled(true);  // Kích hoạt hiệu ứng khi di chuột qua nút

        // Khi hover, thay đổi màu nền của nút
        btnSuaChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaChuDe.setBackground(new java.awt.Color(34, 139, 34));  // Màu nền xanh lá đậm khi hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaChuDe.setBackground(new java.awt.Color(50, 205, 50));  // Trở lại màu xanh lá sáng khi không hover
            }
        });
        // Thay đổi màu nền và màu chữ cho nút bình thường
        jButton1.setBackground(new java.awt.Color(128,128,128));  // Màu nền xanh dương
        jButton1.setForeground(new java.awt.Color(255,255,255));  // Màu chữ trắng

        // Thay đổi font chữ
        jButton1.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));

        // Tạo hiệu ứng khi chuột di chuyển qua nút (hover)
        jButton1.setRolloverEnabled(true);  // Kích hoạt hiệu ứng khi di chuột qua nút

        // Thay đổi màu nền khi hover
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1.setBackground(new java.awt.Color(255, 165, 0));  // Màu nền cam khi hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1.setBackground(new java.awt.Color(128,128,128));  // Trở lại màu xanh dương khi không hover
            }
        });
        // Thay đổi màu nền và màu chữ cho nút bình thường
        btnThemChuDe.setBackground(new java.awt.Color(0,255,255));  // Màu nền xanh dương
        btnThemChuDe.setForeground(new java.awt.Color(255,255,255));  // Màu chữ trắng

        // Thay đổi font chữ
        btnThemChuDe.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));

        // Tạo hiệu ứng khi chuột di chuyển qua nút (hover)
        btnThemChuDe.setRolloverEnabled(true);  // Kích hoạt hiệu ứng khi di chuột qua nút

        // Thay đổi màu nền khi hover
        btnThemChuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemChuDe.setBackground(new java.awt.Color(255, 165, 0));  // Màu nền cam khi hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemChuDe.setBackground(new java.awt.Color(0,255,255));  // Trở lại màu xanh dương khi không hover
            }
        });

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Câu Hỏi");

        jButton2.setText("Thêm");
        jButton2.setToolTipText("Thêm vào chủ đề hoặc thêm mới");

        jButton3.setText("Xóa");
        jButton3.setToolTipText("Xóa khỏi chủ đề hoặc xóa hẳn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        // Tạo model bảng với các tiêu đề cột
        DefaultTableModel tableModel = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "", "Ảnh", "Nội dung", "Mức độ", "Chủ đề"
            }
        ) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return (columnIndex == 0) ? Boolean.class : String.class; // Cột đầu là checkbox
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0; // Chỉ chỉnh sửa checkbox
            }
        };

        // Lấy danh sách câu hỏi từ database
        QuestionsBUS questionBUS = new QuestionsBUS();
        ArrayList<QuestionsDTO> questions = questionBUS.getAll();

        for (QuestionsDTO question : questions) {
            // Tạo mảng chứa dữ liệu cho mỗi câu hỏi
            Object[] row = new Object[5];
            row[0] = false; // Checkbox mặc định là chưa chọn
            row[1] = question.getqPicture(); // Ảnh (nếu có đường dẫn ảnh, bạn có thể hiển thị nó hoặc để trống)
            row[2] = question.getqContent(); // Nội dung câu hỏi
            row[3] = question.getqLevel(); // Mức độ (có thể là "Dễ", "Trung Bình", "Khó", tùy theo dữ liệu của bạn)
            row[4] = question.getqTopicID(); // Chủ đề (có thể thay thế bằng tên chủ đề nếu bạn có thêm thông tin)

            // Thêm hàng vào model bảng
            tableModel.addRow(row);
        }

        // Gán model cho JTable
        table_question.setModel(tableModel);

        // 1️⃣ Căn giữa tiêu đề cột
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) table_question.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // 2️⃣ Căn giữa nội dung của cột cuối cùng ("Mức độ")
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Xác định cột cuối cùng (cột "Mức độ")
        int lastColumnIndex = table_question.getColumnCount() - 1;
        table_question.getColumnModel().getColumn(lastColumnIndex).setCellRenderer(centerRenderer);

        // Căn giữa nội dung của cột "Mức độ"
        table_question.getColumnModel().getColumn(lastColumnIndex-1).setCellRenderer(centerRenderer);

        // Thu hẹp độ rộng của cột "Chủ đề"
        table_question.getColumnModel().getColumn(lastColumnIndex).setPreferredWidth(80);  // Độ rộng mong muốn
        table_question.getColumnModel().getColumn(lastColumnIndex).setMaxWidth(100);       // Độ rộng tối đa
        table_question.getColumnModel().getColumn(lastColumnIndex).setMinWidth(60);        // Độ rộng tối thiểu

        // Căn giữa nội dung của cột "Chủ đề"
        table_question.getColumnModel().getColumn(lastColumnIndex).setCellRenderer(centerRenderer);

        // Thu hẹp độ rộng của cột "Mức độ"
        table_question.getColumnModel().getColumn(lastColumnIndex-1).setPreferredWidth(80);  // Độ rộng mong muốn
        table_question.getColumnModel().getColumn(lastColumnIndex-1).setMaxWidth(100);       // Độ rộng tối đa
        table_question.getColumnModel().getColumn(lastColumnIndex-1).setMinWidth(60);        // Độ rộng tối thiểu

        // 5️⃣ Thu hẹp độ rộng của cột "Ảnh"
        table_question.getColumnModel().getColumn(1).setPreferredWidth(100);  // Độ rộng mong muốn cho cột "Ảnh"
        table_question.getColumnModel().getColumn(1).setMaxWidth(200);        // Độ rộng tối đa cho cột "Ảnh"
        table_question.getColumnModel().getColumn(1).setMinWidth(50);        // Độ rộng tối thiểu cho cột "Ảnh"

        // 4️⃣ Thu hẹp độ rộng của cột checkbox
        table_question.getColumnModel().getColumn(0).setPreferredWidth(40);  // Độ rộng mong muốn cho cột checkbox
        table_question.getColumnModel().getColumn(0).setMaxWidth(50);       // Độ rộng tối đa cho cột checkbox
        table_question.getColumnModel().getColumn(0).setMinWidth(30);        // Độ rộng tối thiểu cho cột checkbox
        jScrollPane2.setViewportView(table_question);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 199, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        // Thay đổi màu nền và màu chữ cho nút bình thường
        jButton2.setBackground(new java.awt.Color(0, 123, 255));  // Màu nền xanh dương
        jButton2.setForeground(new java.awt.Color(255, 255, 255));  // Màu chữ trắng

        // Thay đổi font chữ
        jButton2.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));

        // Tạo hiệu ứng khi chuột di chuyển qua nút (hover)
        jButton2.setRolloverEnabled(true);  // Kích hoạt hiệu ứng khi di chuột qua nút

        // Thay đổi màu nền khi hover
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2.setBackground(new java.awt.Color(255, 165, 0));  // Màu nền cam khi hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2.setBackground(new java.awt.Color(0, 123, 255));  // Trở lại màu xanh dương khi không hover
            }
        });
        // Thay đổi màu nền và màu chữ cho nút bình thường
        jButton3.setBackground(new java.awt.Color(255, 69, 0));  // Màu nền đỏ cam (RGB: 255, 69, 0)
        jButton3.setForeground(new java.awt.Color(255, 255, 255));  // Màu chữ trắng

        // Thay đổi font chữ
        jButton3.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));

        // Tạo hiệu ứng khi chuột di chuyển qua nút (hover)
        jButton3.setRolloverEnabled(true);  // Kích hoạt hiệu ứng khi di chuột qua nút

        // Khi hover, thay đổi màu nền của nút
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3.setBackground(new java.awt.Color(255, 99, 71));  // Màu nền đỏ sáng khi hover
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3.setBackground(new java.awt.Color(255, 69, 0));  // Trở lại màu đỏ cam khi không hover
            }
        });

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThemChuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChuDeActionPerformed
    ThemChuDeDialog dialog = new ThemChuDeDialog(null, true);
    dialog.setLocationRelativeTo(null); // Place the dialog in the center of the screen
    dialog.setVisible(true);
    }//GEN-LAST:event_btnThemChuDeActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        jTree2.setModel(null);
        loadTopics();
    }//GEN-LAST:event_ResetActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
       DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree2.getLastSelectedPathComponent();
if (selectedNode != null) {
      int confirm = JOptionPane.showConfirmDialog(
            null,
            "Bạn có chắc chắn muốn thêm chủ đề này?",
            "Xác nhận",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
    String nodeContent = selectedNode.toString(); // Lấy nội dung của node
    int topicID = topicsBUS.getTopicIdByName(nodeContent);
    TopicsDTO topic = topicsBUS.getTopicByID(topicID);
    TopicsDTO topic_update = new TopicsDTO(topic.getTpID(),topic.getTpTitle(),topic.getTpParent(),0);
    topicsBUS.update(topic_update);
    loadTopics();
          JOptionPane.showMessageDialog(null, "Bạn đã xóa thành công", "Xác nhận", JOptionPane.INFORMATION_MESSAGE);
        } 
} else {
             JOptionPane.showMessageDialog(null, "Hãy chọn một chủ đề", "Nhắc nhở", JOptionPane.INFORMATION_MESSAGE);
}

    }


    
    public void loadTopics() {
    try {
        TopicsDAO topicsDAO = new TopicsDAO();
        ArrayList<TopicsDTO> topics = topicsDAO.getAll();
        
        jTree2.setModel(null); // Xóa toàn bộ cây
        // Tạo node gốc
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Tất cả");

        // Sử dụng HashMap để lưu node theo ID
        Map<Integer, DefaultMutableTreeNode> nodeMap = new HashMap<>();
        nodeMap.put(0, root); // Gốc có tpParent = 0

        // Lặp qua danh sách các chủ đề
        for (TopicsDTO topic : topics) {
            if(topic.getTpStatus() == 1){
                            DefaultMutableTreeNode node = new DefaultMutableTreeNode(topic.getTpTitle());
            nodeMap.put(topic.getTpID(), node);
            
            // Thêm vào node cha dựa vào tpParent
            DefaultMutableTreeNode parent = nodeMap.get(topic.getTpParent());
            if (parent != null) {
                parent.add(node);
            } else {
                // Nếu không tìm thấy parent, có thể là lỗi dữ liệu hoặc tpParent là 0
                root.add(node); // Thêm vào root nếu không có parent
            }
            }
        }

        // Gán dữ liệu vào JTree
        jTree2.setModel(new DefaultTreeModel(root));

    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton btnSuaChuDe;
    private javax.swing.JButton btnThemChuDe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree2;
    private javax.swing.JTable table_question;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.add(new QuestionPanel());
        frame.setSize(1040, 700);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}
