/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.qlthitracnghiem.GUI.DeThi;

/**
 *
 * @author truon
 */
public class Question extends javax.swing.JPanel {

    /**
     * Creates new form Question
     */
    public Question() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paragraph1 = new com.example.qlthitracnghiem.GUI.Component.Paragraph();
        paragraph2 = new com.example.qlthitracnghiem.GUI.Component.Paragraph();
        paragraph3 = new com.example.qlthitracnghiem.GUI.Component.Paragraph();
        paragraph4 = new com.example.qlthitracnghiem.GUI.Component.Paragraph();
        paragraph5 = new com.example.qlthitracnghiem.GUI.Component.Paragraph();

        setMaximumSize(new java.awt.Dimension(600, 160));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        paragraph1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_user_30.png"))); // NOI18N
        paragraph1.setText("<html><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p></html>");
        paragraph1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(paragraph1);

        paragraph2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_user_30.png"))); // NOI18N
        paragraph2.setText("<html><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p></html>");
        paragraph2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(paragraph2);

        paragraph3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_user_30.png"))); // NOI18N
        paragraph3.setText("<html><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p></html>");
        paragraph3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(paragraph3);

        paragraph4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_user_30.png"))); // NOI18N
        paragraph4.setText("<html><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p></html>");
        paragraph4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(paragraph4);

        paragraph5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_user_30.png"))); // NOI18N
        paragraph5.setText("<html><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p></html>");
        paragraph5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(paragraph5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.example.qlthitracnghiem.GUI.Component.Paragraph paragraph1;
    private com.example.qlthitracnghiem.GUI.Component.Paragraph paragraph2;
    private com.example.qlthitracnghiem.GUI.Component.Paragraph paragraph3;
    private com.example.qlthitracnghiem.GUI.Component.Paragraph paragraph4;
    private com.example.qlthitracnghiem.GUI.Component.Paragraph paragraph5;
    // End of variables declaration//GEN-END:variables
}
