/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.qlthitracnghiem.GUI.DeThi;

/**
 *
 * @author truon
 */
public class TestDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestDetailsPanel
     */
    public TestDetailsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCenter = new javax.swing.JPanel();
        questionOpntionsPanel1 = new com.example.qlthitracnghiem.GUI.CauHoi.QuestionOpntionsPanel();
        questionOpntionsPanel2 = new com.example.qlthitracnghiem.GUI.CauHoi.QuestionOpntionsPanel();
        questionOpntionsPanel3 = new com.example.qlthitracnghiem.GUI.CauHoi.QuestionOpntionsPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ten de thi");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(849, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnlCenter.setLayout(new javax.swing.BoxLayout(pnlCenter, javax.swing.BoxLayout.Y_AXIS));

        questionOpntionsPanel1.setPreferredSize(new java.awt.Dimension(1000, 400));
        pnlCenter.add(questionOpntionsPanel1);

        questionOpntionsPanel2.setPreferredSize(new java.awt.Dimension(1000, 400));
        pnlCenter.add(questionOpntionsPanel2);

        questionOpntionsPanel3.setPreferredSize(new java.awt.Dimension(1000, 400));
        pnlCenter.add(questionOpntionsPanel3);

        jScrollPane1.setViewportView(pnlCenter);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCenter;
    private com.example.qlthitracnghiem.GUI.CauHoi.QuestionOpntionsPanel questionOpntionsPanel1;
    private com.example.qlthitracnghiem.GUI.CauHoi.QuestionOpntionsPanel questionOpntionsPanel2;
    private com.example.qlthitracnghiem.GUI.CauHoi.QuestionOpntionsPanel questionOpntionsPanel3;
    // End of variables declaration//GEN-END:variables
}
