/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.qlthitracnghiem.GUI.Exam;

import com.example.qlthitracnghiem.BUS.AnswersBUS;
import com.example.qlthitracnghiem.BUS.QuestionsBUS;
import com.example.qlthitracnghiem.DTO.AnswersDTO;
import com.example.qlthitracnghiem.DTO.QuestionsDTO;
import com.example.qlthitracnghiem.utils.ImageUtil;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JRadioButton;

/**
 *
 * @author truon
 */
public class QuestionPN extends javax.swing.JPanel {

    /**
     * Creates new form QuestionPanel
     */
    // thiet ke sinh vien listbox combobox label, them xoa sinh vien
    private final QuestionsBUS quesBUS = new QuestionsBUS();
    private final AnswersBUS ansBUS = new AnswersBUS();

    private ButtonGroup btnGroup;
    private Map<JRadioButton, AnswersDTO> mapValues;

    private int questOrder;
    private int quesId;

    private QuestionsDTO quesDTO;

    public QuestionPN(int numbOrder, int quesId) {
        this.questOrder = numbOrder;
        this.quesId = quesId;
        mapValues = new HashMap<>();
        btnGroup = new ButtonGroup();
        initComponents();
//        ImageUtil.setIcon(questContentLB, "/icons/ic_user_30.png", 100, 80);
        myInitComponent();
    }

    private void myInitComponent() {
        this.quesDTO = quesBUS.getQuestionDTOById(quesId);
        contentLabel.setText("Câu " + questOrder + ": " + quesDTO.getqContent());
        ImageUtil.setIcon(contentLabel, quesDTO.getqPicture(), 100, 80);
        addAnswerForQuestion(quesId);
    }

    private void addAnswerForQuestion(int quesId) {
        ArrayList<AnswersDTO> ansList = ansBUS.getAnswersByQuestionID(quesId);
        int order = 65; // ASCII code for 'A'

        for (AnswersDTO ans : ansList) {
            char optText = (char) order;
            AnswerOptionPN ansPN = new AnswerOptionPN(btnGroup, ans);
            ansPN.setButtonText(String.valueOf(optText)); // Convert char to String
            ansPN.setParagraph(ans.getAwContent());
            ansPN.setImge(ans.getAwPictures());
//            System.out.println(ansPN.getJRadioButton());
            mapValues.put(ansPN.getJRadioButton(), ans);
            this.add(ansPN);

            // Increment order to move to the next letter
            order++;
        }
    }

    public AnswersDTO getSelectedAnswer() {
        ButtonModel selectedModel = btnGroup.getSelection();
        if (selectedModel != null) {
            Enumeration<AbstractButton> buttons = btnGroup.getElements();
            while (buttons.hasMoreElements()) {
                AbstractButton btn = buttons.nextElement();
                if (btn.getModel() == selectedModel) {
                    return mapValues.get(btn);
                }
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ansBtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        contentLabel = new javax.swing.JLabel();

        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 1000));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        contentLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        contentLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_user_30.png"))); // NOI18N
        contentLabel.setText("<html><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p></html>");
        contentLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(contentLabel);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        javax.swing.JFrame frame = new javax.swing.JFrame();
        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        frame.setSize(1200, 800);
        frame.setLayout(new java.awt.FlowLayout());

//        QuestionPN questionPanel = new QuestionPN();
//        frame.add(questionPanel);
//        System.out.println(questionPanel.getPreferredSize());
//        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ansBtnGroup;
    private javax.swing.JLabel contentLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
